server:
  port: 8081

spring:
  zipkin:
    #zipkin中心地址
    base-url: http://localhost:9411
    #发送数据类型 kafaka、rabbitmq、web
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  ### mybatis配置
  datasource:
    url: jdbc:mysql://localhost:3306/lost?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  ### sentinel dashboard
  cloud:
    sentinel:
      transport:
        eager: true
        port: 8791
        dashboard: localhost:9090

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.shibo.lost.entity

### actuator/refresh 热部署
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info

feign:
#  hystrix:
#    enabled: true
  sentinel:
    enabled: true
ribbon:
  ReadTimeout: 1000000
## 是否开启自动配置
#rocketmq:
#  producer:
#    isOnOff: on
##    groupName: # 发送同一类消息设置为同一个group，保证唯一默认不需要设置，rocketmq会使用ip@pid（pid代表jvm名字）作为唯一标识
#    namesrvAddr: 127.0.0.1:9876 # mq的nameserver地址
#  # 消息最大长度 默认 1024 * 4 (4M)
#    maxMessageSize: 4096
#  # 发送消息超时时间，默认 3000
#    sendMsgTimeOut: 3000
#  # 发送消息失败重试次数，默认2
#    retryTimesWhenSendFailed: 2
#

xc:
  rocketmq2:
    topic-string: topic_string
    string-consumer-group: string_consumer_group
#    topic-user: topic_user
#    user-consumer-group: user_consumer_group
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: producer_group_test

