server:
  port: 8081

spring:
  zipkin:
    #zipkin中心地址
    base-url: http://localhost:9411
    #发送数据类型 kafaka、rabbitmq、web
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  ### mybatis配置
  datasource:
    url: jdbc:mysql://localhost:3306/lost?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.shibo.lost.entity

### actuator/refresh 热部署
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info

feign:
  hystrix:
    enabled: true
