server:
  port: 8081

spring:
  zipkin:
    #zipkin中心地址
    base-url: http://localhost:9411
    #发送数据类型 kafaka、rabbitmq、web
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

### actuator/refresh 热部署
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info
        
feign:
  hystrix:
    enabled: true